name: Build and push image to ECR

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Check out codes
      uses: actions/checkout@v2

    - name: Install Utilities
      run: |
        sudo apt-get update
        sudo apt-get install -y jq unzip

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: your-aws-region
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION

    - name: Build and push Docker image to ECR
      run: |
        # Your Docker build and push commands go here
        # Example:
        # docker build -t your-ecr-repo-url/your-image-name:latest .
        # docker push your-ecr-repo-url/your-image-name:latest
